---
- hosts: all
  sudo: true
  vars_files:
    - ../../Config/ansible/vars/all.yml
  roles:
    - server
    - vagrant_local
    - nginx
    - mysql
    - php
    - composer
    - nodesource.node
    - app
