---
# application tasks to be customized and to run after the main provision
- name: global bower
  npm: name=bower global=yes

- name: global grunt-cli
  npm: name=grunt-cli global=yes

- name: npm install
  npm: path=/vagrant

- name: composer install
  composer: command=install working_dir=/vagrant

- name: bower install
  command: "bower install"
  args:
    chdir: /vagrant
  sudo: no

- name: grunt
  command: "grunt"
  args:
    chdir: /vagrant
  sudo: no

- name: copy Config/database.php
  command: "cp database.php.default database.php"
  args:
    chdir: /vagrant/Config
    creates: /vagrant/Config/database.php

- name: adminer
  get_url:
    url: "http://www.adminer.org/latest-mysql-en.php"
    dest: /vagrant/webroot/ad.php
    mode: 0644
    force: true
